@startuml
' Classe principale Utilisateur 
' Le forfait sera identifié par soit D, I OU A
class Utilisateur {
  - nom: String
  - courriel: String
  - numéro_téléphone: String
  - adresse_domicile: String
  - date_naissance: Date
  - mot_de_passe: String
  - forfait: Forfait
  - carte_de_crédit: CarteDeCrédit
}

' Carte de Crédit
class CarteDeCrédit {
  - type: String <<enum>> {VISA, MasterCard, Amex}
  - numéro: String
  - date_expiration: Date
  - cvv: String
}

' Forfait
class Forfait {
  - coût: double
  - locations_max: int
  - durée_max: int
}

' Location
class Location {
  - start_date: Date
  - due_date: Date
  - returned_date: Date
  - Copie: copie
}

' Film
class Film {
  - titre: String
  - année_sortie: int
  - pays_production: String
  - langue: String
  - durée: int
  - genres: String[]
  - réalisateur: Réalisateur
  - acteurs: Acteur[]
  - scénaristes: Scénariste[]
  - résumé: String
  - affiche: String
  - liens: String[]
}

' Réalisateur
class Réalisateur {
  - nom: String
  - films: Film[]
}

' Scénariste
class Scénariste {
  - nom: String
  - films: Film[]
}

' Acteur
class Acteur {
  - rôles: Rôle[]
}

' Rôle
class Rôle {
  - nom: StringS
  - film: Film
  - description: String
}

' Personne (classe parent)
class Personne {
  - nom: String
  - date_naissance: Date
  - lieu_naissance: String
  - photo: String
  - biographie: String
}

' Classe Copie pour les copies de films
class Copie {
  - disponible: Bool
  - film: Film
}

' Associations
Utilisateur "1" -- "1" CarteDeCrédit : possède
Utilisateur "1" -- "1" Forfait : souscrit à
Utilisateur "1" -- "0..*" Location : loue


Location "1" -- "1" Copie : utilise_copie

Film "1" -- "0..*" Réalisateur : réalisé par
Film "0..*" -- "0..*" Acteur : inclus
Film "0..*" -- "0..*" Scénariste : écrit par
Film "1" -- "0..*" Copie : a_des_copies

Personne <|-- Réalisateur
Personne <|-- Acteur
Personne <|-- Scénariste
Acteur "1" -- "0..*" Rôle : joue dans

@enduml
